"""add lat and lon columns to table tower

Revision ID: bcef16f30c7e
Revises: 6de02d6b2682
Create Date: 2019-08-18 11:00:22.636048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcef16f30c7e'
down_revision = '6de02d6b2682'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tower', sa.Column('lat', sa.Numeric(), nullable=True))
    op.add_column('tower', sa.Column('lon', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tower', 'lon')
    op.drop_column('tower', 'lat')
    # ### end Alembic commands ###
